name: Redeploy on Render

on: 
  push:
    branches:
      - master

jobs:
  redeploy_on_render:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger front-end redeploy
        run: |
          curl -X GET \
            https://api.render.com/deploy/srv-cqhrppks1f4s73ambm8g?key=IO2pyehJaj8
